/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ResetPasswordRouteImport } from './../routes/reset-password'
import { Route as RegisterRouteImport } from './../routes/register'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as ConfirmEmailRouteImport } from './../routes/confirm-email'
import { Route as AuthenticatedRouteImport } from './../routes/_authenticated'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as InvitationsAcceptRouteImport } from './../routes/invitations.accept'
import { Route as AuthenticatedSettingsRouteImport } from './../routes/_authenticated.settings'
import { Route as AuthenticatedProjectsRouteImport } from './../routes/_authenticated.projects'
import { Route as AuthenticatedArchiveRouteImport } from './../routes/_authenticated.archive'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './../routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdSwimlaneRouteImport } from './../routes/_authenticated.projects.$projectId.swimlane'
import { Route as AuthenticatedProjectsProjectIdSettingsRouteImport } from './../routes/_authenticated.projects.$projectId.settings'
import { Route as AuthenticatedProjectsProjectIdGanttRouteImport } from './../routes/_authenticated.projects.$projectId.gantt'
import { Route as AuthenticatedProjectsProjectIdBoardsBoardIdRouteImport } from './../routes/_authenticated.projects.$projectId.boards.$boardId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdSwimlaneRoute =
  AuthenticatedProjectsProjectIdSwimlaneRouteImport.update({
    id: '/swimlane',
    path: '/swimlane',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsRoute =
  AuthenticatedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdGanttRoute =
  AuthenticatedProjectsProjectIdGanttRouteImport.update({
    id: '/gantt',
    path: '/gantt',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdBoardsBoardIdRoute =
  AuthenticatedProjectsProjectIdBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/gantt': typeof AuthenticatedProjectsProjectIdGanttRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/swimlane': typeof AuthenticatedProjectsProjectIdSwimlaneRoute
  '/projects/$projectId/boards/$boardId': typeof AuthenticatedProjectsProjectIdBoardsBoardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/gantt': typeof AuthenticatedProjectsProjectIdGanttRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/projects/$projectId/swimlane': typeof AuthenticatedProjectsProjectIdSwimlaneRoute
  '/projects/$projectId/boards/$boardId': typeof AuthenticatedProjectsProjectIdBoardsBoardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/$projectId/gantt': typeof AuthenticatedProjectsProjectIdGanttRoute
  '/_authenticated/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsRoute
  '/_authenticated/projects/$projectId/swimlane': typeof AuthenticatedProjectsProjectIdSwimlaneRoute
  '/_authenticated/projects/$projectId/boards/$boardId': typeof AuthenticatedProjectsProjectIdBoardsBoardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/archive'
    | '/projects'
    | '/settings'
    | '/invitations/accept'
    | '/projects/$projectId'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/swimlane'
    | '/projects/$projectId/boards/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/archive'
    | '/projects'
    | '/settings'
    | '/invitations/accept'
    | '/projects/$projectId'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/swimlane'
    | '/projects/$projectId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confirm-email'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/archive'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/invitations/accept'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/$projectId/gantt'
    | '/_authenticated/projects/$projectId/settings'
    | '/_authenticated/projects/$projectId/swimlane'
    | '/_authenticated/projects/$projectId/boards/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId/swimlane': {
      id: '/_authenticated/projects/$projectId/swimlane'
      path: '/swimlane'
      fullPath: '/projects/$projectId/swimlane'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSwimlaneRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings': {
      id: '/_authenticated/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/gantt': {
      id: '/_authenticated/projects/$projectId/gantt'
      path: '/gantt'
      fullPath: '/projects/$projectId/gantt'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdGanttRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/boards/$boardId': {
      id: '/_authenticated/projects/$projectId/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/projects/$projectId/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBoardsBoardIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdGanttRoute: typeof AuthenticatedProjectsProjectIdGanttRoute
  AuthenticatedProjectsProjectIdSettingsRoute: typeof AuthenticatedProjectsProjectIdSettingsRoute
  AuthenticatedProjectsProjectIdSwimlaneRoute: typeof AuthenticatedProjectsProjectIdSwimlaneRoute
  AuthenticatedProjectsProjectIdBoardsBoardIdRoute: typeof AuthenticatedProjectsProjectIdBoardsBoardIdRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdGanttRoute:
      AuthenticatedProjectsProjectIdGanttRoute,
    AuthenticatedProjectsProjectIdSettingsRoute:
      AuthenticatedProjectsProjectIdSettingsRoute,
    AuthenticatedProjectsProjectIdSwimlaneRoute:
      AuthenticatedProjectsProjectIdSwimlaneRoute,
    AuthenticatedProjectsProjectIdBoardsBoardIdRoute:
      AuthenticatedProjectsProjectIdBoardsBoardIdRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
